# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df5f852e85ef5e9fa9fd6351abb4a802924af6cd87636d475eb1ef89e547af71bfc93b79cbc06332bfcc9c9f23890fe22cb544f2d16529199e58ccc909d4fbb1

test:
  secret_key_base: b2cc1a24ee3119b224f47f39099df7cc4183168b1753993cb62f3c43c0cc14c046a6bf7fe7e44a465aedba16b2105aa66013ce2cc2ba2bb3dc34072c5c4018d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
